### ISSUE TITLE
author disambiguation: feature selection

### ISSUE THREAD

**Issue by glouppe** [inveniosoftware/beard#54]
* [ ] Decide on a final set of features for author disambiguation
* [ ] Modify `author-disambiguation/distance.py` accordingly
* [ ] Add a flag for fast disambiguation, using a restricted set of features

**Comment by glouppe** [comment]
See also #42

**Comment by MSusik** [comment]
One of the features that should be checked is similarity of so-called `Subject Categories`.

**Comment by natsheh** [comment]
Based on some experiments I run last week, I recommend keeping all and also add the "topics" and the "race_estimator" feature. In case we want to remove some features for the computation time cost, I would unfortunately vote for removing only the best feature which is "co-authors-similarity". since it is the most slow feature (consumes ~50% of the total time) while using all except it leads to very small loss of accuracy.

I would need to make a PR with the beard/similarity/pairs.py where I will add the transformers of the "race_estimator" feature. I would also need to upload the race_estimator file itself somewhere here in the author disambiguation example folder.

**Comment by kaplun** [comment]
As usual I am out of the technical details, but related to co-authors: is the comparison slow also in case of few co-authors? 

Because one easy(?) thing we could do is to acknowledge the difference between experimental papers (written by large collaboration) and theoretical papers (written by at most 10~15 people).

Would consider co-author only in the case of they are less than 15, and using the collaboration information, when available, help in this case?

**Comment by natsheh** [comment]
The version of co-authors feature I am referring to is actually a faster one than considering all the co-authors. The faster one considers a window of up to 10 co-authors before and 10 after the author. This assumes that the authors list keeps the same ordering. This strategy has been proven to be much faster without loosing a considerable accuracy value. This faster version is what I am referring to in the above comment. The good news is that we can just keep it and handle the time cost with a powerful machine that can run the whole process within 24 hours, or we can decide not to use it as the other features combined provide very close accuracy measure value. To show it in figures:
# all features: 0.9807 accuracy  ,, more than 4 hours on 10 % of the data
# all except co-authors: 0.9789 accuracy ,, less than 2 hours on 10% of the data

**Comment by glouppe** [comment]
The example now includes a `--fast` flag.
